window.BJJ_FLOW_DATA = {
  defaultNodeId: "standing",
  maxIncomingHints: 4,
  incomingHintThreshold: 5,
  groups: [
    { id: "stand", label: "立ち技・入口" },
    { id: "guard", label: "ガード" },
    { id: "sweep", label: "スイープ" },
    { id: "pass", label: "パス" },
    { id: "control", label: "トップコントロール" },
    { id: "submission", label: "サブミッション" },
    { id: "escape", label: "エスケープ" },
  ],
  types: [
    { id: "position", label: "ポジション" },
    { id: "entry", label: "入口" },
    { id: "takedown", label: "テイクダウン" },
    { id: "guard", label: "ガード" },
    { id: "sweep", label: "スイープ" },
    { id: "pass", label: "パス" },
    { id: "control", label: "コントロール" },
    { id: "submission", label: "極め" },
    { id: "escape", label: "脱出" },
  ],
  nodes: [
    {
      id: "standing",
      label: "スタンディング",
      group: "stand",
      type: "position",
      title: "立ち技の開始位置",
      summary: "距離、姿勢、グリップを管理しながら、倒す・引き込む・背中を取る入口を探す。",
      backgroundWord: "立ち技",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "良い姿勢、先手のグリップ、角度を作る" },
        { label: "入口", value: "グリップファイト、クリンチ、ガードプル" },
        { label: "注意", value: "首を下げすぎず、片足を軽くしすぎない" },
      ],
    },
    {
      id: "grip-fight",
      label: "グリップファイト",
      group: "stand",
      type: "entry",
      title: "先に触って角度を作る",
      summary: "袖、襟、手首、首、内側差しを取り合い、次のテイクダウンや引き込みを安全に作る。",
      backgroundWord: "GRIP",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "相手の姿勢を崩し、自分の入口を先に作る" },
        { label: "使うもの", value: "襟、袖、手首、カラータイ、アームドラッグ" },
        { label: "注意", value: "両手を伸ばし切らず、頭の位置を失わない" },
      ],
    },
    {
      id: "collar-tie",
      label: "カラータイ",
      group: "stand",
      type: "entry",
      title: "首と頭の位置を支配する",
      summary: "首の後ろを押さえ、頭の位置と前後の崩しからスナップダウンやシングルレッグへ入る。",
      backgroundWord: "首",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "頭の位置を勝ち、相手の姿勢を前に落とす" },
        { label: "接続", value: "スナップダウン、ギロチン、シングルレッグ" },
        { label: "注意", value: "強く引くだけでなく、横角度を同時に作る" },
      ],
    },
    {
      id: "arm-drag",
      label: "アームドラッグ",
      group: "stand",
      type: "entry",
      title: "腕を流して背中側へ入る",
      summary: "相手の腕を横へ流し、正面の力を避けながらバック、ボディロック、シングルレッグへつなぐ。",
      backgroundWord: "DRAG",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "相手の正面を外し、背中側の角度を取る" },
        { label: "接続", value: "バックテイク、ボディロック、シングルレッグ" },
        { label: "注意", value: "腕だけを引かず、自分の足も同時に入れる" },
      ],
    },
    {
      id: "snap-down",
      label: "スナップダウン",
      group: "stand",
      type: "entry",
      title: "頭を落として前方を開く",
      summary: "首や頭を下へ落とし、フロントヘッドロック、タートル、ギロチンへ移行する入口。",
      backgroundWord: "SNAP",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "相手の手をマットに着かせ、首と肩を支配する" },
        { label: "接続", value: "フロントヘッドロック、タートル、ギロチン" },
        { label: "注意", value: "真下に引くだけでなく、斜め下へ落とす" },
      ],
    },
    {
      id: "single-leg",
      label: "シングルレッグ",
      group: "stand",
      type: "takedown",
      title: "片脚を捕まえて倒す",
      summary: "片脚を抱え、頭の位置と角度で相手のバランスを崩してトップへつなげる。",
      backgroundWord: "片脚",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "片脚を軽くして、相手を横か後ろへ倒す" },
        { label: "接続", value: "ハーフガード、サイドコントロール、レッグドラッグ" },
        { label: "注意", value: "首を抱えられないよう頭を外側に安定させる" },
      ],
    },
    {
      id: "double-leg",
      label: "ダブルレッグ",
      group: "stand",
      type: "takedown",
      title: "両脚をまとめて押し切る",
      summary: "レベルチェンジから両脚へ入り、角度を切って倒してパスまたはトップコントロールへ入る。",
      backgroundWord: "DOUBLE",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "両膝のラインを崩し、相手をマットへ運ぶ" },
        { label: "接続", value: "サイドコントロール、ハーフガードトップ" },
        { label: "注意", value: "膝を遠くに着かず、頭を相手の体に密着させる" },
      ],
    },
    {
      id: "ankle-pick",
      label: "アンクルピック",
      group: "stand",
      type: "takedown",
      title: "足首を拾って崩す",
      summary: "襟や頭を下げながら足首を拾い、相手の支点を消してトップに入る。",
      backgroundWord: "足首",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "頭と足首を逆方向へ動かして倒す" },
        { label: "接続", value: "トレアンドパス、ニーオンベリー、サイド" },
        { label: "注意", value: "手だけで足を追わず、上半身の崩しを先に作る" },
      ],
    },
    {
      id: "body-lock",
      label: "ボディロック",
      group: "stand",
      type: "takedown",
      title: "胴を抱えて密着する",
      summary: "両腕で胴をロックし、足技、崩し、マットリターンからトップへ移行する。",
      backgroundWord: "LOCK",
      theme: "stand",
      drawing: "standing",
      facts: [
        { label: "目的", value: "腰を近づけ、相手の回転と距離を消す" },
        { label: "接続", value: "内掛け、外掛け、バックコントロール" },
        { label: "注意", value: "頭を相手の中心より高く保ち、投げ返しを防ぐ" },
      ],
    },
    {
      id: "guard-pull",
      label: "ガードプル",
      group: "stand",
      type: "entry",
      title: "立ちからガードへ引き込む",
      summary: "相手を倒す代わりに、自分の得意なガードへ安全に引き込み、スイープや極めを狙う。",
      backgroundWord: "PULL",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "相手のベースを残したまま、自分の攻撃的ガードに入る" },
        { label: "接続", value: "クローズド、オープン、バタフライ、デラヒーバ" },
        { label: "注意", value: "距離が遠いまま座らず、グリップを作ってから引く" },
      ],
    },
    {
      id: "closed-guard",
      label: "クローズドガード",
      group: "guard",
      type: "guard",
      title: "相手の腰を閉じ込める",
      summary: "両脚を相手の腰の後ろで組み、姿勢を壊して腕十字、三角、スイープへつなぐ。",
      backgroundWord: "CLOSED",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "姿勢を崩し、腕と首を孤立させる" },
        { label: "攻撃", value: "三角絞め、腕十字、キムラ、花スイープ" },
        { label: "注意", value: "相手の姿勢を立て直される前に角度を作る" },
      ],
    },
    {
      id: "open-guard",
      label: "オープンガード",
      group: "guard",
      type: "guard",
      title: "脚で距離と角度を作る",
      summary: "足、すね、フック、グリップを使い、相手を動かしながらスイープとサブミッションを作る。",
      backgroundWord: "OPEN",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "距離を調整し、相手のベースを片側へ寄せる" },
        { label: "派生", value: "バタフライ、デラヒーバ、スパイダー、Xガード" },
        { label: "注意", value: "膝と肘の内側を守り、簡単に胸を合わせさせない" },
      ],
    },
    {
      id: "butterfly-guard",
      label: "バタフライガード",
      group: "guard",
      type: "guard",
      title: "内側フックで浮かせる",
      summary: "両足を相手の内ももに入れ、上体の引き込みとフックで相手を浮かせるガード。",
      backgroundWord: "HOOK",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "相手の重心を前に乗せ、片側へ倒す" },
        { label: "攻撃", value: "バタフライスイープ、Xガード、フロントヘッド" },
        { label: "注意", value: "背中を丸めすぎず、頭と胸を近づけて座る" },
      ],
    },
    {
      id: "de-la-riva",
      label: "デラヒーバ",
      group: "guard",
      type: "guard",
      title: "外側フックで立ち相手を崩す",
      summary: "相手の脚に外側からフックし、袖や足首を使って横方向の崩しを作る。",
      backgroundWord: "DLR",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "立っている相手の足を固定し、背中側へ回る" },
        { label: "攻撃", value: "ベリンボロ、シングルレッグX、デラヒーバスイープ" },
        { label: "注意", value: "膝を潰される前に角度と距離を保つ" },
      ],
    },
    {
      id: "spider-guard",
      label: "スパイダーガード",
      group: "guard",
      type: "guard",
      title: "袖と足で腕を支配する",
      summary: "袖を持ち、足裏を上腕や二頭筋に置いて相手の姿勢と手の自由を奪う。",
      backgroundWord: "SPIDER",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "腕を伸ばし、相手のパス方向を制限する" },
        { label: "攻撃", value: "三角絞め、オモプラッタ、スイープ" },
        { label: "注意", value: "袖を切られたらすぐ別ガードへ切り替える" },
      ],
    },
    {
      id: "lasso-guard",
      label: "ラッソーガード",
      group: "guard",
      type: "guard",
      title: "袖に脚を巻いて止める",
      summary: "袖グリップと脚の巻き込みで相手の片腕を固定し、パスを遅らせて崩しを作る。",
      backgroundWord: "LASSO",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "片腕を消して、相手の姿勢と方向を制限する" },
        { label: "攻撃", value: "ラッソースイープ、三角、オモプラッタ" },
        { label: "注意", value: "脚を深く入れすぎて膝を固定されないようにする" },
      ],
    },
    {
      id: "x-guard",
      label: "Xガード",
      group: "guard",
      type: "guard",
      title: "脚を絡めて立ち相手を浮かせる",
      summary: "相手の片脚の下に入り、両脚でX字に支えてベースを崩す強力なスイープ位置。",
      backgroundWord: "X",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "相手の片脚を浮かせ、前後左右のベースを奪う" },
        { label: "攻撃", value: "テクニカルスタンドアップ、バック、レッグドラッグ" },
        { label: "注意", value: "上半身を潰される前に距離を作る" },
      ],
    },
    {
      id: "single-leg-x",
      label: "シングルレッグX",
      group: "guard",
      type: "guard",
      title: "片脚を軸に崩す",
      summary: "相手の片脚に自分の腰を寄せ、足首と膝のラインを支配してスイープや脚関節へ入る。",
      backgroundWord: "SLX",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "片脚を孤立させ、相手の立ち姿勢を不安定にする" },
        { label: "攻撃", value: "ストレートフットロック、Xガード、スイープ" },
        { label: "注意", value: "足をまたがれて膝を外側に潰されないようにする" },
      ],
    },
    {
      id: "half-guard",
      label: "ハーフガード",
      group: "guard",
      type: "guard",
      title: "片脚を絡めて止める",
      summary: "相手の片脚を自分の両脚で絡め、アンダーフックや膝シールドから上を取り返す。",
      backgroundWord: "HALF",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "パスを止め、アンダーフックから起き上がる" },
        { label: "攻撃", value: "オールドスクール、ディープハーフ、キムラ" },
        { label: "注意", value: "クロスフェイスを許すと背中を潰されやすい" },
      ],
    },
    {
      id: "knee-shield",
      label: "ニーシールド",
      group: "guard",
      type: "guard",
      title: "膝で距離を作るハーフ",
      summary: "上の膝を相手の胸や肩に当て、圧力を止めながらアンダーフックやフレームを作る。",
      backgroundWord: "SHIELD",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "距離を保ち、潰される前に角度を作る" },
        { label: "攻撃", value: "アンダーフック、キムラ、ディープハーフ" },
        { label: "注意", value: "膝を内側に畳まれないよう足先まで使う" },
      ],
    },
    {
      id: "deep-half",
      label: "ディープハーフ",
      group: "guard",
      type: "guard",
      title: "相手の下に潜る",
      summary: "相手の重心の真下へ入り、片脚を抱えて前後へ揺らしながらスイープを作る。",
      backgroundWord: "DEEP",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "相手の腰の下に入り、重心を自分の上に乗せる" },
        { label: "攻撃", value: "ウェイタースイープ、バックドア、Xガード" },
        { label: "注意", value: "首を抱えられない位置に頭を置く" },
      ],
    },
    {
      id: "fifty-fifty",
      label: "50/50ガード",
      group: "guard",
      type: "guard",
      title: "脚を対称に絡める",
      summary: "互いの脚が絡んだ中立的な位置から、スイープ、足関節、上の取り合いを行う。",
      backgroundWord: "50/50",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "相手の脚を固定し、上を取るか足関節へ移る" },
        { label: "攻撃", value: "アンクルロック、トーホールド、ヒールフック" },
        { label: "注意", value: "ルールセットごとの脚関節制限を確認する" },
      ],
    },
    {
      id: "rubber-guard",
      label: "ラバーガード",
      group: "guard",
      type: "guard",
      title: "姿勢を折って上半身を固定する",
      summary: "柔軟性を使い、脚で相手の姿勢を押さえながら片腕を自由にして極めを狙う。",
      backgroundWord: "RUBBER",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "目的", value: "相手の姿勢を低く固定し、腕や首を攻める" },
        { label: "攻撃", value: "オモプラッタ、三角、ゴゴプラッタ" },
        { label: "注意", value: "膝や股関節に無理をかけない" },
      ],
    },
    {
      id: "closed-guard-break",
      label: "クローズドガード解除",
      group: "pass",
      type: "pass",
      title: "閉じた脚を開かせる",
      summary: "姿勢を立て、腰と膝の位置を使ってクローズドガードを開き、パスの入口を作る。",
      backgroundWord: "BREAK",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "相手の脚を開かせ、膝を中に入れる" },
        { label: "接続", value: "スタンディング解除、ニーカット、スタック" },
        { label: "注意", value: "腕を孤立させず、姿勢を崩されない" },
      ],
    },
    {
      id: "standing-break",
      label: "立ち上がり解除",
      group: "pass",
      type: "pass",
      title: "立ってガードを開く",
      summary: "安全な姿勢で立ち上がり、腰の角度と膝の押し込みで脚を開かせる方法。",
      backgroundWord: "STAND",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "相手の腰を遠ざけ、脚のロックを弱める" },
        { label: "接続", value: "トレアンド、レッグドラッグ、Xパス" },
        { label: "注意", value: "足首をすくわれる前にグリップを切る" },
      ],
    },
    {
      id: "knee-cut-pass",
      label: "ニーカットパス",
      group: "pass",
      type: "pass",
      title: "膝でラインを割る",
      summary: "膝を相手の腿を越えて滑らせ、上半身のフレームを潰しながらサイドへ進む。",
      backgroundWord: "CUT",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "膝のラインを越えて、腰と肩を同時に制圧する" },
        { label: "接続", value: "サイドコントロール、ニーオンベリー、マウント" },
        { label: "注意", value: "アンダーフックを取られたまま進まない" },
      ],
    },
    {
      id: "toreando-pass",
      label: "トレアンドパス",
      group: "pass",
      type: "pass",
      title: "脚を捌いて横へ回る",
      summary: "相手の脚を横へ流し、正面を避けて素早くサイドへ回るブルファイターパス。",
      backgroundWord: "TOR",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "脚のフレームを横へ外し、胸を合わせる" },
        { label: "接続", value: "サイド、ニーオンベリー、レッグドラッグ" },
        { label: "注意", value: "距離を取りすぎて再ガードを許さない" },
      ],
    },
    {
      id: "leg-drag-pass",
      label: "レッグドラッグ",
      group: "pass",
      type: "pass",
      title: "脚を横へ運んで背中側へ回る",
      summary: "相手の脚を自分の腰の外へ運び、腰の向きを固定してバックやサイドへ移行する。",
      backgroundWord: "DRAG",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "腰を横向きに固定し、再ガードの足を消す" },
        { label: "接続", value: "サイドコントロール、バック、マウント" },
        { label: "注意", value: "相手の上半身を自由にさせない" },
      ],
    },
    {
      id: "over-under-pass",
      label: "オーバーアンダーパス",
      group: "pass",
      type: "pass",
      title: "片脚を抱えて圧力で抜ける",
      summary: "片脚を肩で抱え、反対側を押さえながら重さで腰を潰してサイドへ進む。",
      backgroundWord: "圧力",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "腰の向きを潰し、脚を一つずつ越える" },
        { label: "接続", value: "サイド、ノースサウス、スマッシュ" },
        { label: "注意", value: "三角やギロチンに頭を入れすぎない" },
      ],
    },
    {
      id: "body-lock-pass",
      label: "ボディロックパス",
      group: "pass",
      type: "pass",
      title: "腰を抱えて動きを止める",
      summary: "相手の腰を密着して抱え、膝と足のフレームを少しずつ越えてパスする。",
      backgroundWord: "BODY",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "腰を固定し、足の再配置を遅らせる" },
        { label: "接続", value: "ハーフトップ、サイド、マウント" },
        { label: "注意", value: "頭を中心に置き、背中を取られない" },
      ],
    },
    {
      id: "stack-pass",
      label: "スタックパス",
      group: "pass",
      type: "pass",
      title: "相手を折り畳んで通る",
      summary: "足を持ち上げて腰を頭側へ積み、脚の可動域を制限して横へ抜ける。",
      backgroundWord: "STACK",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "腰を高く上げ、ガードの角度を潰す" },
        { label: "接続", value: "サイド、ノースサウス、腕十字防御" },
        { label: "注意", value: "首へ危険な圧をかけすぎない" },
      ],
    },
    {
      id: "smash-pass",
      label: "スマッシュパス",
      group: "pass",
      type: "pass",
      title: "脚を畳んで圧をかける",
      summary: "相手の膝と腰を内側へ畳み、上半身の重さで動きを止めて越える。",
      backgroundWord: "SMASH",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "膝を胸へ近づけ、腰の回転を消す" },
        { label: "接続", value: "サイド、マウント、ノースサウス" },
        { label: "注意", value: "フレームを残したまま胸を合わせない" },
      ],
    },
    {
      id: "x-pass",
      label: "Xパス",
      group: "pass",
      type: "pass",
      title: "足を外して一気に角度を取る",
      summary: "相手の足を外しながら斜め前へステップし、オープンガードの外側へ回る。",
      backgroundWord: "X-PASS",
      theme: "pass",
      drawing: "pass",
      facts: [
        { label: "目的", value: "足先のフレームを切り、外側の角度を取る" },
        { label: "接続", value: "ニーオンベリー、サイド、レッグドラッグ" },
        { label: "注意", value: "上半身を先に倒されないよう姿勢を高く保つ" },
      ],
    },
    {
      id: "side-control",
      label: "サイドコントロール",
      group: "control",
      type: "control",
      title: "横から胸を合わせて押さえる",
      summary: "相手の上半身を横から制圧し、マウント、ニーオンベリー、ノースサウス、極めへつなぐ。",
      backgroundWord: "SIDE",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "肩と腰を止め、再ガードを防ぐ" },
        { label: "攻撃", value: "キムラ、アメリカーナ、マウント、ニーオン" },
        { label: "注意", value: "腰を軽くしすぎるとエビで戻される" },
      ],
    },
    {
      id: "kesa-gatame",
      label: "袈裟固め",
      group: "control",
      type: "control",
      title: "頭と腕を抱える横四方",
      summary: "頭と腕を抱えて胸を斜めに当て、相手の上体を強く固定するポジション。",
      backgroundWord: "袈裟",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "頭と肩のラインを固定し、起き上がりを止める" },
        { label: "攻撃", value: "アームロック、マウント移行、ノースサウス" },
        { label: "注意", value: "背中側へ回られないよう腰の位置を保つ" },
      ],
    },
    {
      id: "north-south",
      label: "ノースサウス",
      group: "control",
      type: "control",
      title: "頭側から上半身を制圧する",
      summary: "互いの体が反対向きになるトップ位置。首、肩、腕を固定して絞めやキムラを狙う。",
      backgroundWord: "N/S",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "頭と肩を挟み、相手の腰の逃げを遅らせる" },
        { label: "攻撃", value: "ノースサウスチョーク、キムラ、サイド復帰" },
        { label: "注意", value: "頭を遠くに置きすぎず、胸圧を保つ" },
      ],
    },
    {
      id: "knee-on-belly",
      label: "ニーオンベリー",
      group: "control",
      type: "control",
      title: "膝で圧をかけて移動する",
      summary: "膝を腹や胸に置き、相手の反応を引き出しながらマウントや極めへ移る。",
      backgroundWord: "KNEE",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "相手を動かし、腕や首の隙間を作る" },
        { label: "攻撃", value: "マウント、腕十字、ベースボールチョーク" },
        { label: "注意", value: "膝だけに乗らず、足と手でベースを取る" },
      ],
    },
    {
      id: "mount",
      label: "マウント",
      group: "control",
      type: "control",
      title: "正面から上を取る",
      summary: "相手の胴体の上に乗り、腰と膝で逃げを抑えながら腕や首を孤立させる。",
      backgroundWord: "MOUNT",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "相手の腰を止め、腕を頭上へ上げさせる" },
        { label: "攻撃", value: "腕十字、肩固め、エゼキエル、バック" },
        { label: "注意", value: "足を軽くしすぎるとブリッジで返される" },
      ],
    },
    {
      id: "technical-mount",
      label: "テクニカルマウント",
      group: "control",
      type: "control",
      title: "横向きのマウントで腕を孤立させる",
      summary: "相手が横を向いた瞬間に膝と足で挟み、腕十字やバックテイクを狙う。",
      backgroundWord: "S-MOUNT",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "横向きの相手を固定し、腕と背中を攻める" },
        { label: "攻撃", value: "腕十字、バック、ボウアンドアロー" },
        { label: "注意", value: "上体を前に倒しすぎて下から戻されない" },
      ],
    },
    {
      id: "back-control",
      label: "バックコントロール",
      group: "control",
      type: "control",
      title: "背中から支配する",
      summary: "相手の背中に胸を合わせ、フックやボディトライアングルで逃げを止めて絞めを狙う。",
      backgroundWord: "BACK",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "胸と背中を密着させ、肩のラインを支配する" },
        { label: "攻撃", value: "リアネイキッド、送り襟絞め、腕十字" },
        { label: "注意", value: "頭を同じ側に置き続け、肩を床につけさせない" },
      ],
    },
    {
      id: "turtle",
      label: "タートル",
      group: "control",
      type: "position",
      title: "四つん這いの攻防",
      summary: "防御側が丸まり、攻撃側は背中、首、腰を狙う。守る側はガード復帰や立ち上がりを探す。",
      backgroundWord: "TURTLE",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "攻撃側は背中を取り、防御側は内側を守る" },
        { label: "接続", value: "バック、フロントヘッド、ガード復帰" },
        { label: "注意", value: "首と脇を同時に開けない" },
      ],
    },
    {
      id: "front-headlock",
      label: "フロントヘッドロック",
      group: "control",
      type: "control",
      title: "首と腕を前から束ねる",
      summary: "相手の頭を下げた状態で首と腕を制御し、ギロチン、ダース、アナコンダ、バックへつなぐ。",
      backgroundWord: "HEAD",
      theme: "control",
      drawing: "control",
      facts: [
        { label: "目的", value: "頭を下げたまま肩のラインを回す" },
        { label: "攻撃", value: "ギロチン、ダース、アナコンダ、バック" },
        { label: "注意", value: "相手の腰を自由にさせると立たれやすい" },
      ],
    },
    {
      id: "scissor-sweep",
      label: "シザースイープ",
      group: "sweep",
      type: "sweep",
      title: "膝とすねで横へ切る",
      summary: "クローズドガードから相手のベースを片側へ寄せ、脚をハサミのように使って返す。",
      backgroundWord: "SCISSOR",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "入口", value: "クローズドガード、襟袖グリップ" },
        { label: "出口", value: "マウント、トップハーフ、サイド" },
        { label: "注意", value: "相手の膝を外へ開かせてから切る" },
      ],
    },
    {
      id: "hip-bump-sweep",
      label: "ヒップバンプ",
      group: "sweep",
      type: "sweep",
      title: "腰をぶつけて上を取る",
      summary: "相手が姿勢を立てた瞬間に起き上がり、腰で押してマウントへ返す。",
      backgroundWord: "BUMP",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "入口", value: "クローズドガード、相手の手が後ろにある時" },
        { label: "出口", value: "マウント、キムラ、ギロチン" },
        { label: "注意", value: "腕だけで押さず、腰を相手の胸へ入れる" },
      ],
    },
    {
      id: "flower-sweep",
      label: "花スイープ",
      group: "sweep",
      type: "sweep",
      title: "腕と脚を引き出して回す",
      summary: "クローズドガードから片腕と片脚をコントロールし、斜めに回転してマウントを取る。",
      backgroundWord: "FLOWER",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "入口", value: "クローズドガード、袖または腕の支配" },
        { label: "出口", value: "マウント、腕十字、三角" },
        { label: "注意", value: "真横ではなく斜め前へ相手を倒す" },
      ],
    },
    {
      id: "tripod-sweep",
      label: "トライポッドスイープ",
      group: "sweep",
      type: "sweep",
      title: "足首と腰を逆方向へ崩す",
      summary: "オープンガードから足首を持ち、反対足で腰を押して立ち相手を後方へ倒す。",
      backgroundWord: "TRIPOD",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "入口", value: "オープンガード、相手が立っている時" },
        { label: "出口", value: "トップ、レッグドラッグ、アンクルロック" },
        { label: "注意", value: "片足を押すだけでなく、足首を固定する" },
      ],
    },
    {
      id: "sickle-sweep",
      label: "シックスイープ",
      group: "sweep",
      type: "sweep",
      title: "外側から脚を刈る",
      summary: "立っている相手の片脚を外側から刈り、反対側のベースを奪って倒す。",
      backgroundWord: "SICKLE",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "入口", value: "オープンガード、デラヒーバ、シングルレッグX" },
        { label: "出口", value: "トップ、パス、足関節" },
        { label: "注意", value: "相手の手を自由にさせるとポストされる" },
      ],
    },
    {
      id: "butterfly-sweep",
      label: "バタフライスイープ",
      group: "sweep",
      type: "sweep",
      title: "フックで浮かせて返す",
      summary: "内側フックで相手を浮かせ、上体の引き込みと角度で横へ返す。",
      backgroundWord: "ELEVATE",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "入口", value: "バタフライガード、オーバーアンダー" },
        { label: "出口", value: "マウント、サイド、Xガード" },
        { label: "注意", value: "背中を先に倒さず、相手の重さを自分に乗せる" },
      ],
    },
    {
      id: "old-school-sweep",
      label: "オールドスクール",
      group: "sweep",
      type: "sweep",
      title: "ハーフから足を拾って返す",
      summary: "ハーフガードでアンダーフックを取り、相手の遠い足を拾って前へ崩す。",
      backgroundWord: "OLD",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "入口", value: "ハーフガード、アンダーフック" },
        { label: "出口", value: "トップハーフ、サイド、バック" },
        { label: "注意", value: "クロスフェイスを切ってから起き上がる" },
      ],
    },
    {
      id: "waiter-sweep",
      label: "ウェイタースイープ",
      group: "sweep",
      type: "sweep",
      title: "ディープハーフから盆を運ぶように返す",
      summary: "相手の脚を抱えてバランスを浮かせ、片側へ起き上がってトップを取る。",
      backgroundWord: "WAITER",
      theme: "guard",
      drawing: "guard",
      facts: [
        { label: "入口", value: "ディープハーフ、片脚の抱え込み" },
        { label: "出口", value: "トップ、レッグドラッグ、Xガード" },
        { label: "注意", value: "頭を外に出しすぎず、腰の下に残る" },
      ],
    },
    {
      id: "rear-naked-choke",
      label: "リアネイキッドチョーク",
      group: "submission",
      type: "submission",
      title: "背中から首を絞める",
      summary: "バックコントロールから腕を首に回し、肩と二頭筋で両側を閉じる代表的な絞め。",
      backgroundWord: "RNC",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "バックコントロール、シートベルト" },
        { label: "要点", value: "顎ではなく首の側面を閉じる" },
        { label: "注意", value: "腕を深く入れる前に肩のラインを保つ" },
      ],
    },
    {
      id: "bow-and-arrow",
      label: "送り襟絞め",
      group: "submission",
      type: "submission",
      title: "襟と脚で弓の形を作る",
      summary: "バックから襟を深く持ち、脚で距離を作りながら首を絞める道着の強力な攻撃。",
      backgroundWord: "襟絞",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "バック、テクニカルマウント" },
        { label: "要点", value: "襟を深く取り、肩を相手の背中に残す" },
        { label: "注意", value: "上に逃げられる前に腰を外側へ切る" },
      ],
    },
    {
      id: "triangle-choke",
      label: "三角絞め",
      group: "submission",
      type: "submission",
      title: "脚で首と腕を閉じる",
      summary: "片腕を内側に残し、脚で三角形を作って頸動脈を圧迫する。",
      backgroundWord: "三角",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "クローズド、スパイダー、ラッソー" },
        { label: "要点", value: "角度を切り、膝裏を首に深くかける" },
        { label: "注意", value: "真正面で閉じるだけだと姿勢で逃げられる" },
      ],
    },
    {
      id: "armbar",
      label: "腕十字",
      group: "submission",
      type: "submission",
      title: "肘を伸ばして極める",
      summary: "相手の親指を上に向け、腰を支点にして肘関節を伸展させる基本の関節技。",
      backgroundWord: "腕十字",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "クローズド、マウント、バック、ニーオン" },
        { label: "要点", value: "膝を締め、親指方向を管理する" },
        { label: "注意", value: "腰を遠ざけず、肩のラインを支配する" },
      ],
    },
    {
      id: "kimura",
      label: "キムラ",
      group: "submission",
      type: "submission",
      title: "肩を内側へ捻る",
      summary: "リバース腕絡みで肩をコントロールし、ガード、ハーフ、サイドから攻撃と移行を作る。",
      backgroundWord: "KIMURA",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "クローズド、ハーフ、サイド、ノースサウス" },
        { label: "要点", value: "手首と肘を固定し、肩を床から離す" },
        { label: "注意", value: "腕力だけで捻らず、体の角度で動かす" },
      ],
    },
    {
      id: "americana",
      label: "アメリカーナ",
      group: "submission",
      type: "submission",
      title: "肩を外側へ捻る",
      summary: "マウントやサイドから相手の腕をL字に固定し、肩関節を外旋方向へ極める。",
      backgroundWord: "KEYLOCK",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "サイド、マウント、袈裟固め" },
        { label: "要点", value: "手首を床に固定し、肘を腰側へ近づける" },
        { label: "注意", value: "腕だけを押さず、肩を浮かせない" },
      ],
    },
    {
      id: "omoplata",
      label: "オモプラッタ",
      group: "submission",
      type: "submission",
      title: "脚で肩を捻る",
      summary: "脚を相手の腕にかけ、うつ伏せ方向へ崩しながら肩を極める技。",
      backgroundWord: "OMO",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "クローズド、スパイダー、ラッソー、ラバー" },
        { label: "要点", value: "腰を外に出し、相手の前転を止める" },
        { label: "注意", value: "肩の上に体重を残し、距離を詰める" },
      ],
    },
    {
      id: "guillotine",
      label: "ギロチン",
      group: "submission",
      type: "submission",
      title: "前から首を包む",
      summary: "首を前から抱え、相手の頭を下げたまま喉や頸動脈を圧迫する。",
      backgroundWord: "GUILLOTINE",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "スナップダウン、フロントヘッド、ガード" },
        { label: "要点", value: "首だけでなく肩のラインも閉じる" },
        { label: "注意", value: "背中を床に寝かされる前に角度を作る" },
      ],
    },
    {
      id: "arm-triangle",
      label: "肩固め",
      group: "submission",
      type: "submission",
      title: "腕と首をまとめて絞める",
      summary: "相手の腕を首側へ押し込み、自分の肩と頭で圧迫して絞める。",
      backgroundWord: "肩固",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "マウント、サイド、ハーフトップ" },
        { label: "要点", value: "腕を首に密着させ、体を横へ降りる" },
        { label: "注意", value: "腕が首から離れると圧が抜ける" },
      ],
    },
    {
      id: "darce",
      label: "ダースチョーク",
      group: "submission",
      type: "submission",
      title: "脇下から首を通す絞め",
      summary: "相手の脇下から腕を通して首を包み、肩と腕で斜めに絞める。",
      backgroundWord: "D'ARCE",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "フロントヘッド、ハーフトップ、タートル" },
        { label: "要点", value: "腕を深く通し、相手の肩を耳へ寄せる" },
        { label: "注意", value: "浅いまま握ると首だけが抜ける" },
      ],
    },
    {
      id: "anaconda",
      label: "アナコンダチョーク",
      group: "submission",
      type: "submission",
      title: "首と腕を巻き込んで転がす",
      summary: "フロントヘッドから腕を深く回し、ロールで角度を作って絞める。",
      backgroundWord: "ANACONDA",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "フロントヘッド、スナップダウン" },
        { label: "要点", value: "首と腕をまとめ、相手を横へ転がす" },
        { label: "注意", value: "腕のロックを浅くしない" },
      ],
    },
    {
      id: "north-south-choke",
      label: "ノースサウスチョーク",
      group: "submission",
      type: "submission",
      title: "頭側から首を包む",
      summary: "ノースサウスから首の片側を腕で包み、胸と肩で圧を作るノーギでも強い絞め。",
      backgroundWord: "N/S",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "ノースサウス、サイド" },
        { label: "要点", value: "肩を首に密着させ、体を低く伸ばす" },
        { label: "注意", value: "相手の顎だけを押さえない" },
      ],
    },
    {
      id: "ezekiel",
      label: "エゼキエルチョーク",
      group: "submission",
      type: "submission",
      title: "袖や前腕で首を閉じる",
      summary: "マウントやガード内から袖や前腕を使って首の前後を挟む絞め。",
      backgroundWord: "EZEKIEL",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "マウント、クローズドガード内、サイド" },
        { label: "要点", value: "片腕を首の後ろ、反対腕を喉へ入れる" },
        { label: "注意", value: "押すだけでなく胸を落として空間を消す" },
      ],
    },
    {
      id: "baseball-choke",
      label: "ベースボールチョーク",
      group: "submission",
      type: "submission",
      title: "襟をバットのように握る",
      summary: "両手で襟を握り、角度を変えて首を挟む道着の絞め。ニーオンやサイドから狙いやすい。",
      backgroundWord: "BASEBALL",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "ニーオンベリー、サイド、下からのカウンター" },
        { label: "要点", value: "両手の距離を近くし、体を回して締める" },
        { label: "注意", value: "上を失うリスクを理解して仕掛ける" },
      ],
    },
    {
      id: "straight-ankle-lock",
      label: "ストレートフットロック",
      group: "submission",
      type: "submission",
      title: "足首をまっすぐ反らす",
      summary: "相手の足首を脇に挟み、前腕と背中の反りで足首を伸展させる基本の足関節。",
      backgroundWord: "ANKLE",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "シングルレッグX、50/50、アシガラミ" },
        { label: "要点", value: "膝を挟み、足首のラインを逃がさない" },
        { label: "注意", value: "ルールと帯ごとの制限を確認する" },
      ],
    },
    {
      id: "kneebar",
      label: "膝十字",
      group: "submission",
      type: "submission",
      title: "膝を伸ばして極める",
      summary: "相手の脚を自分の体で挟み、膝関節を伸展方向へ極めるレッグロック。",
      backgroundWord: "KNEEBAR",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "50/50、サドル、バックサイド50、タートル横" },
        { label: "要点", value: "膝のラインを自分の腰より上に残す" },
        { label: "注意", value: "回転逃げとヒール露出に注意する" },
      ],
    },
    {
      id: "toe-hold",
      label: "トーホールド",
      group: "submission",
      type: "submission",
      title: "足首をひねる",
      summary: "足先を抱えて足首を回旋させるレッグロック。50/50やトップから狙いやすい。",
      backgroundWord: "TOE",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "50/50、オープンガード、トップレッグコントロール" },
        { label: "要点", value: "足先だけでなく膝の向きも固定する" },
        { label: "注意", value: "反撃の足関節を受けやすい" },
      ],
    },
    {
      id: "heel-hook",
      label: "ヒールフック",
      group: "submission",
      type: "submission",
      title: "踵を回して膝を攻める",
      summary: "踵を固定して膝に回旋力をかける強力な足関節。ルールセットによって制限が大きい。",
      backgroundWord: "HEEL",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "サドル、50/50、シングルレッグX" },
        { label: "要点", value: "膝のラインを抜かせず、踵を露出させる" },
        { label: "注意", value: "練習では特にゆっくり、早めにタップする" },
      ],
    },
    {
      id: "calf-slicer",
      label: "カーフスライサー",
      group: "submission",
      type: "submission",
      title: "ふくらはぎを圧迫する",
      summary: "相手の膝裏に自分の脛や前腕を入れ、脚を折り畳んで圧迫するコンプレッションロック。",
      backgroundWord: "CALF",
      theme: "submit",
      drawing: "submission",
      facts: [
        { label: "入口", value: "タートル、トラック、レッグコントロール" },
        { label: "要点", value: "膝裏に支点を作り、足首を引き込む" },
        { label: "注意", value: "大会ルールで禁止される場合がある" },
      ],
    },
    {
      id: "shrimp-escape",
      label: "エビ",
      group: "escape",
      type: "escape",
      title: "腰を逃がしてスペースを作る",
      summary: "フレームを作り、腰を横へ逃がして膝を入れ直す最重要の脱出動作。",
      backgroundWord: "エビ",
      theme: "escape",
      drawing: "escape",
      facts: [
        { label: "目的", value: "胸の圧をずらし、膝と肘をつなげる" },
        { label: "使う場面", value: "サイド、マウント、ニーオン" },
        { label: "注意", value: "相手を押すより、自分の腰を動かす" },
      ],
    },
    {
      id: "bridge-roll",
      label: "ブリッジロール",
      group: "escape",
      type: "escape",
      title: "橋を作って返す",
      summary: "相手の片側のポストを消し、腰の爆発力で斜め上へ返すマウント脱出。",
      backgroundWord: "UPA",
      theme: "escape",
      drawing: "escape",
      facts: [
        { label: "目的", value: "片腕片脚を封じ、相手を支えられなくする" },
        { label: "使う場面", value: "マウント、低いマウント" },
        { label: "注意", value: "真上ではなく斜め肩越しに返す" },
      ],
    },
    {
      id: "elbow-knee-escape",
      label: "肘膝エスケープ",
      group: "escape",
      type: "escape",
      title: "肘と膝をつなげて戻す",
      summary: "マウントやサイドから肘と膝の空間を閉じ、ハーフやガードへ戻す脱出。",
      backgroundWord: "肘膝",
      theme: "escape",
      drawing: "escape",
      facts: [
        { label: "目的", value: "内側スペースを作り、脚を入れ直す" },
        { label: "使う場面", value: "マウント、サイド、ニーオン" },
        { label: "注意", value: "腕を伸ばさず、フレームを短く強く作る" },
      ],
    },
    {
      id: "side-control-escape",
      label: "サイド脱出",
      group: "escape",
      type: "escape",
      title: "フレームからガードへ戻す",
      summary: "首と腰にフレームを作り、エビで膝を差し込みハーフまたはオープンガードへ戻す。",
      backgroundWord: "ESCAPE",
      theme: "escape",
      drawing: "escape",
      facts: [
        { label: "目的", value: "肩と腰の固定を外し、膝を内側へ戻す" },
        { label: "出口", value: "ハーフ、クローズド、タートル" },
        { label: "注意", value: "首を押すだけでなく腰のフレームも作る" },
      ],
    },
    {
      id: "mount-escape",
      label: "マウント脱出",
      group: "escape",
      type: "escape",
      title: "腰を動かして下から戻る",
      summary: "ブリッジ、肘膝、足抜きを組み合わせ、ハーフガードやクローズドガードへ戻す。",
      backgroundWord: "脱出",
      theme: "escape",
      drawing: "escape",
      facts: [
        { label: "目的", value: "相手の膝をずらし、片脚を絡める" },
        { label: "出口", value: "ハーフ、クローズド、タートル" },
        { label: "注意", value: "腕を伸ばして腕十字を与えない" },
      ],
    },
    {
      id: "back-escape",
      label: "バック脱出",
      group: "escape",
      type: "escape",
      title: "絞め手を守って床へ逃げる",
      summary: "首を守り、肩を床へ落としてフックを外し、トップまたはガードへ戻る。",
      backgroundWord: "BACK OUT",
      theme: "escape",
      drawing: "escape",
      facts: [
        { label: "目的", value: "絞め手を先に防ぎ、肩をマットへ落とす" },
        { label: "出口", value: "トップハーフ、ガード、タートル" },
        { label: "注意", value: "首の防御を後回しにしない" },
      ],
    },
    {
      id: "turtle-recovery",
      label: "タートルリカバリー",
      group: "escape",
      type: "escape",
      title: "四つん這いから戻る",
      summary: "首と脇を守りながら、ガード、立ち上がり、シングルレッグへ戻る防御の流れ。",
      backgroundWord: "RECOVER",
      theme: "escape",
      drawing: "escape",
      facts: [
        { label: "目的", value: "背中を取らせず、内側スペースを取り返す" },
        { label: "出口", value: "ガード、スタンディング、シングルレッグ" },
        { label: "注意", value: "両脇を開けたまま止まらない" },
      ],
    },
  ],
  edges: [
    { from: "standing", to: "grip-fight", label: "グリップを作る", summary: "最初に触って姿勢と角度の主導権を取る。", relation: "入口", primary: true },
    { from: "standing", to: "guard-pull", label: "ガードへ引き込む", summary: "倒し合いを避け、自分の得意なガードから攻める。", relation: "入口" },
    { from: "standing", to: "single-leg", label: "片脚へ入る", summary: "レベルチェンジから片脚を捕まえる。", relation: "テイクダウン" },
    { from: "standing", to: "double-leg", label: "両脚へ入る", summary: "両脚をまとめてトップへ進む。", relation: "テイクダウン" },
    { from: "standing", to: "body-lock", label: "胴を抱える", summary: "距離を消して足技やバックへつなぐ。", relation: "クリンチ" },
    { from: "grip-fight", to: "collar-tie", label: "首を支配する", summary: "カラータイから頭の位置を勝つ。", relation: "入口", primary: true },
    { from: "grip-fight", to: "arm-drag", label: "腕を流す", summary: "正面を外して背中側の角度へ入る。", relation: "角度" },
    { from: "grip-fight", to: "guard-pull", label: "安全に引き込む", summary: "グリップを持ったままガードへ入る。", relation: "入口" },
    { from: "collar-tie", to: "snap-down", label: "頭を落とす", summary: "相手を前に崩して首を攻める。", relation: "崩し", primary: true },
    { from: "collar-tie", to: "single-leg", label: "片脚へ切り替える", summary: "頭の反応に合わせてレベルチェンジする。", relation: "テイクダウン" },
    { from: "arm-drag", to: "back-control", label: "背中へ回る", summary: "腕を流した勢いで胸を背中に合わせる。", relation: "バック", primary: true },
    { from: "arm-drag", to: "body-lock", label: "胴を抱える", summary: "背中側から腰を固定する。", relation: "クリンチ" },
    { from: "snap-down", to: "front-headlock", label: "首と腕を束ねる", summary: "頭を下げたままフロントヘッドロックへ入る。", relation: "コントロール", primary: true },
    { from: "snap-down", to: "turtle", label: "タートルへ追う", summary: "相手が手をついたら背中側を攻める。", relation: "追撃" },
    { from: "snap-down", to: "guillotine", label: "ギロチンを狙う", summary: "首が空いた瞬間に前から包む。", relation: "極め" },
    { from: "single-leg", to: "half-guard", label: "ハーフで着地する", summary: "相手が脚を絡めて止める展開。", relation: "着地" },
    { from: "single-leg", to: "side-control", label: "サイドへ倒す", summary: "脚を抜きながら横へ胸を合わせる。", relation: "トップ", primary: true },
    { from: "single-leg", to: "leg-drag-pass", label: "レッグドラッグへ", summary: "捕まえた脚を横へ運んで背中側へ回る。", relation: "パス" },
    { from: "double-leg", to: "side-control", label: "サイドで固める", summary: "倒した勢いを使って胸を合わせる。", relation: "トップ", primary: true },
    { from: "double-leg", to: "closed-guard", label: "ガードに入られる", summary: "相手が脚を閉じて下から攻める展開。", relation: "注意" },
    { from: "ankle-pick", to: "toreando-pass", label: "脚を捌いて回る", summary: "足首を拾った後、オープンガードを越える。", relation: "パス", primary: true },
    { from: "ankle-pick", to: "knee-on-belly", label: "ニーオンへ乗る", summary: "相手の反応を使って移動式の圧へ進む。", relation: "トップ" },
    { from: "body-lock", to: "side-control", label: "倒して横へ固める", summary: "胴を抱えたままサイドへ着地する。", relation: "トップ", primary: true },
    { from: "body-lock", to: "back-control", label: "背中を取る", summary: "相手が背を向けたらバックへ移る。", relation: "バック" },
    { from: "guard-pull", to: "closed-guard", label: "クローズドへ入る", summary: "相手の腰を閉じ込めて姿勢を壊す。", relation: "ガード", primary: true },
    { from: "guard-pull", to: "open-guard", label: "オープンへ入る", summary: "脚とグリップで距離を作る。", relation: "ガード" },
    { from: "guard-pull", to: "butterfly-guard", label: "バタフライへ座る", summary: "内側フックで相手を浮かせる。", relation: "ガード" },
    { from: "guard-pull", to: "de-la-riva", label: "デラヒーバへ", summary: "立ち相手の脚に外側フックを作る。", relation: "ガード" },
    { from: "closed-guard", to: "scissor-sweep", label: "シザースイープ", summary: "襟袖を使って横へ返す。", relation: "スイープ", primary: true },
    { from: "closed-guard", to: "hip-bump-sweep", label: "ヒップバンプ", summary: "姿勢を立てた相手に起き上がって返す。", relation: "スイープ" },
    { from: "closed-guard", to: "flower-sweep", label: "花スイープ", summary: "腕と脚を引き出して斜めに回す。", relation: "スイープ" },
    { from: "closed-guard", to: "triangle-choke", label: "三角を狙う", summary: "片腕を内側に残して脚で首を閉じる。", relation: "極め" },
    { from: "closed-guard", to: "armbar", label: "腕十字へ", summary: "腕を孤立させて角度を作る。", relation: "極め" },
    { from: "closed-guard", to: "kimura", label: "キムラへ", summary: "手をマットについた反応を取る。", relation: "極め" },
    { from: "closed-guard", to: "closed-guard-break", label: "相手が解除を始める", summary: "トップ側のパス入口を確認する。", relation: "相手の選択", muted: true },
    { from: "open-guard", to: "butterfly-guard", label: "内側フックへ", summary: "座って相手を浮かせる形にする。", relation: "派生", primary: true },
    { from: "open-guard", to: "de-la-riva", label: "デラヒーバへ", summary: "立ち相手の外側脚を絡める。", relation: "派生" },
    { from: "open-guard", to: "spider-guard", label: "袖を支配する", summary: "足裏で腕を伸ばして止める。", relation: "派生" },
    { from: "open-guard", to: "lasso-guard", label: "ラッソーへ", summary: "袖に脚を巻いて片腕を止める。", relation: "派生" },
    { from: "open-guard", to: "x-guard", label: "Xガードへ潜る", summary: "片脚の下へ入りベースを崩す。", relation: "派生" },
    { from: "open-guard", to: "tripod-sweep", label: "トライポッド", summary: "足首と腰を逆方向へ崩す。", relation: "スイープ" },
    { from: "open-guard", to: "toreando-pass", label: "相手のトレアンド", summary: "トップ側の代表的な外回りパスを見る。", relation: "相手の選択", muted: true },
    { from: "butterfly-guard", to: "butterfly-sweep", label: "フックで返す", summary: "相手を浮かせて横へ倒す。", relation: "スイープ", primary: true },
    { from: "butterfly-guard", to: "x-guard", label: "Xガードへ入る", summary: "浮いた脚の下に潜る。", relation: "移行" },
    { from: "butterfly-guard", to: "front-headlock", label: "頭を下げさせる", summary: "相手が前へ落ちたら首を取る。", relation: "移行" },
    { from: "de-la-riva", to: "single-leg-x", label: "SLXへ切り替える", summary: "外側フックから片脚軸の崩しに移る。", relation: "移行", primary: true },
    { from: "de-la-riva", to: "sickle-sweep", label: "シックスイープ", summary: "外側から脚を刈って倒す。", relation: "スイープ" },
    { from: "de-la-riva", to: "back-control", label: "背中へ回る", summary: "角度を作ってバックテイクを狙う。", relation: "バック" },
    { from: "spider-guard", to: "triangle-choke", label: "三角へ", summary: "腕を伸ばして首と腕を閉じる。", relation: "極め", primary: true },
    { from: "spider-guard", to: "omoplata", label: "オモプラッタ", summary: "袖の支配から肩を攻める。", relation: "極め" },
    { from: "lasso-guard", to: "omoplata", label: "オモプラッタへ", summary: "ラッソーの腕を肩攻めに変える。", relation: "極め", primary: true },
    { from: "lasso-guard", to: "triangle-choke", label: "三角へ", summary: "腕の位置を利用して脚を回す。", relation: "極め" },
    { from: "x-guard", to: "waiter-sweep", label: "ウェイター系へ", summary: "脚を持ち上げてトップを取る。", relation: "スイープ", primary: true },
    { from: "x-guard", to: "leg-drag-pass", label: "トップでレッグドラッグ", summary: "返した後、脚を横へ流して越える。", relation: "パス" },
    { from: "single-leg-x", to: "straight-ankle-lock", label: "足首を攻める", summary: "片脚を固定してフットロックへ。", relation: "極め", primary: true },
    { from: "single-leg-x", to: "x-guard", label: "Xガードへ拡張", summary: "両脚のコントロールへ切り替える。", relation: "移行" },
    { from: "half-guard", to: "knee-shield", label: "膝で距離を作る", summary: "ニーシールドで圧を止める。", relation: "防御", primary: true },
    { from: "half-guard", to: "old-school-sweep", label: "オールドスクール", summary: "アンダーフックから起き上がって返す。", relation: "スイープ" },
    { from: "half-guard", to: "kimura", label: "キムラを作る", summary: "上半身の反応を肩攻めに変える。", relation: "極め" },
    { from: "knee-shield", to: "deep-half", label: "ディープハーフへ潜る", summary: "圧を利用して腰の下へ入る。", relation: "移行", primary: true },
    { from: "knee-shield", to: "old-school-sweep", label: "アンダーフックで起きる", summary: "横向きのままトップを取り返す。", relation: "スイープ" },
    { from: "deep-half", to: "waiter-sweep", label: "ウェイター", summary: "片脚を抱えてトップへ返す。", relation: "スイープ", primary: true },
    { from: "deep-half", to: "x-guard", label: "Xガードへ", summary: "脚の下から外へ角度を変える。", relation: "移行" },
    { from: "fifty-fifty", to: "straight-ankle-lock", label: "アンクルロック", summary: "足首をまっすぐ反らす。", relation: "極め", primary: true },
    { from: "fifty-fifty", to: "toe-hold", label: "トーホールド", summary: "足首を回旋方向へ攻める。", relation: "極め" },
    { from: "fifty-fifty", to: "heel-hook", label: "ヒールフック", summary: "ルール確認が必要な強力な足関節。", relation: "極め" },
    { from: "rubber-guard", to: "omoplata", label: "オモプラッタ", summary: "姿勢を折ったまま肩を攻める。", relation: "極め", primary: true },
    { from: "rubber-guard", to: "triangle-choke", label: "三角へ", summary: "片腕を残して脚を閉じる。", relation: "極め" },
    { from: "scissor-sweep", to: "mount", label: "マウントで着地", summary: "返した後に上を安定させる。", relation: "出口", primary: true },
    { from: "hip-bump-sweep", to: "mount", label: "マウントへ", summary: "腰で返してそのまま上を取る。", relation: "出口", primary: true },
    { from: "hip-bump-sweep", to: "kimura", label: "キムラへ切り替える", summary: "相手がポストした腕を攻める。", relation: "極め" },
    { from: "flower-sweep", to: "mount", label: "マウントへ", summary: "回転の最後に上へ乗る。", relation: "出口", primary: true },
    { from: "tripod-sweep", to: "leg-drag-pass", label: "レッグドラッグ", summary: "倒した脚を横へ運んで越える。", relation: "出口", primary: true },
    { from: "sickle-sweep", to: "side-control", label: "サイドへ", summary: "倒した後に胸を合わせる。", relation: "出口", primary: true },
    { from: "butterfly-sweep", to: "mount", label: "マウントへ", summary: "相手を返して上から固定する。", relation: "出口", primary: true },
    { from: "old-school-sweep", to: "side-control", label: "サイドへ", summary: "トップを取って脚を抜く。", relation: "出口", primary: true },
    { from: "waiter-sweep", to: "leg-drag-pass", label: "レッグドラッグへ", summary: "相手の脚を持ったまま横へ進む。", relation: "出口", primary: true },
    { from: "closed-guard-break", to: "standing-break", label: "立って開く", summary: "姿勢を立てて脚を開かせる。", relation: "解除", primary: true },
    { from: "closed-guard-break", to: "knee-cut-pass", label: "膝を差す", summary: "開いた瞬間に膝でラインを割る。", relation: "パス" },
    { from: "standing-break", to: "toreando-pass", label: "外回りへ", summary: "脚を横へ流して回る。", relation: "パス", primary: true },
    { from: "standing-break", to: "leg-drag-pass", label: "脚を横へ運ぶ", summary: "片脚を制して腰を固定する。", relation: "パス" },
    { from: "knee-cut-pass", to: "side-control", label: "サイドへ抜ける", summary: "膝を越えたら肩と腰を止める。", relation: "トップ", primary: true },
    { from: "knee-cut-pass", to: "knee-on-belly", label: "ニーオンへ", summary: "抜けた角度から膝で圧を作る。", relation: "トップ" },
    { from: "toreando-pass", to: "side-control", label: "サイドへ回る", summary: "脚を越えたら胸を合わせる。", relation: "トップ", primary: true },
    { from: "toreando-pass", to: "knee-on-belly", label: "ニーオンへ乗る", summary: "相手の腰が横を向いたら膝を置く。", relation: "トップ" },
    { from: "leg-drag-pass", to: "back-control", label: "バックへ", summary: "相手が背を向けたら背中へつく。", relation: "バック", primary: true },
    { from: "leg-drag-pass", to: "side-control", label: "サイドで固める", summary: "腰を固定して胸を合わせる。", relation: "トップ" },
    { from: "over-under-pass", to: "side-control", label: "サイドへ", summary: "脚を越えたら横から固定する。", relation: "トップ", primary: true },
    { from: "over-under-pass", to: "north-south", label: "ノースサウスへ", summary: "頭側へ回って肩を制圧する。", relation: "トップ" },
    { from: "body-lock-pass", to: "side-control", label: "サイドへ", summary: "腰を抱えたまま脚を越える。", relation: "トップ", primary: true },
    { from: "body-lock-pass", to: "mount", label: "マウントへ", summary: "膝を越えたら正面上へ進む。", relation: "トップ" },
    { from: "stack-pass", to: "side-control", label: "サイドへ", summary: "畳んだ脚を横へ捌いて固定する。", relation: "トップ", primary: true },
    { from: "stack-pass", to: "north-south", label: "ノースサウスへ", summary: "頭側へ回って腕を孤立させる。", relation: "トップ" },
    { from: "smash-pass", to: "mount", label: "マウントへ", summary: "膝を畳んだまま上へ登る。", relation: "トップ", primary: true },
    { from: "smash-pass", to: "side-control", label: "サイドへ", summary: "腰を潰して横に胸を合わせる。", relation: "トップ" },
    { from: "x-pass", to: "knee-on-belly", label: "ニーオンへ", summary: "外側の角度から膝を置く。", relation: "トップ", primary: true },
    { from: "x-pass", to: "side-control", label: "サイドへ", summary: "脚を越えたら上半身を固定する。", relation: "トップ" },
    { from: "side-control", to: "mount", label: "マウントへ進む", summary: "膝を腹に通して正面上を取る。", relation: "前進", primary: true },
    { from: "side-control", to: "north-south", label: "ノースサウスへ", summary: "頭側へ回り肩と腕を攻める。", relation: "移行" },
    { from: "side-control", to: "knee-on-belly", label: "ニーオンへ", summary: "相手の反応を出す移動式コントロール。", relation: "移行" },
    { from: "side-control", to: "kimura", label: "キムラ", summary: "腕が床から離れたら肩を取る。", relation: "極め" },
    { from: "side-control", to: "americana", label: "アメリカーナ", summary: "腕がL字になったら肩を攻める。", relation: "極め" },
    { from: "side-control", to: "side-control-escape", label: "相手の脱出を見る", summary: "下側の戻し方を確認する。", relation: "相手の選択", muted: true },
    { from: "kesa-gatame", to: "americana", label: "腕を攻める", summary: "抱えた腕を肩方向へ固定する。", relation: "極め", primary: true },
    { from: "kesa-gatame", to: "mount", label: "マウントへ", summary: "腰を切り替えて正面上へ移る。", relation: "前進" },
    { from: "north-south", to: "north-south-choke", label: "ノースサウスチョーク", summary: "首の側面を肩で閉じる。", relation: "極め", primary: true },
    { from: "north-south", to: "kimura", label: "キムラ", summary: "腕を孤立させて肩を攻める。", relation: "極め" },
    { from: "knee-on-belly", to: "mount", label: "マウントへ", summary: "相手が押した反応で上へ乗る。", relation: "前進", primary: true },
    { from: "knee-on-belly", to: "armbar", label: "腕十字", summary: "押してくる腕を孤立させる。", relation: "極め" },
    { from: "knee-on-belly", to: "baseball-choke", label: "ベースボールチョーク", summary: "襟を握って回転する絞めを作る。", relation: "極め" },
    { from: "mount", to: "technical-mount", label: "横向きを追う", summary: "相手が逃げる方向へ膝を切り替える。", relation: "前進", primary: true },
    { from: "mount", to: "armbar", label: "腕十字", summary: "腕を頭上へ上げさせて孤立させる。", relation: "極め" },
    { from: "mount", to: "arm-triangle", label: "肩固め", summary: "腕を首側へ押し込む。", relation: "極め" },
    { from: "mount", to: "ezekiel", label: "エゼキエル", summary: "袖や前腕で首を閉じる。", relation: "極め" },
    { from: "mount", to: "mount-escape", label: "相手の脱出を見る", summary: "下側の戻し方を確認する。", relation: "相手の選択", muted: true },
    { from: "technical-mount", to: "back-control", label: "バックへ", summary: "相手の背中側へ胸を合わせる。", relation: "バック", primary: true },
    { from: "technical-mount", to: "armbar", label: "腕十字", summary: "孤立した腕をまたいで極める。", relation: "極め" },
    { from: "back-control", to: "rear-naked-choke", label: "裸絞め", summary: "首に腕を入れて肩で閉じる。", relation: "極め", primary: true },
    { from: "back-control", to: "bow-and-arrow", label: "送り襟絞め", summary: "襟を使って道着の絞めへ。", relation: "極め" },
    { from: "back-control", to: "armbar", label: "腕十字", summary: "防御する腕を孤立させる。", relation: "極め" },
    { from: "back-control", to: "back-escape", label: "相手の脱出を見る", summary: "防御側の肩落としを確認する。", relation: "相手の選択", muted: true },
    { from: "turtle", to: "back-control", label: "背中を取る", summary: "シートベルトとフックを入れる。", relation: "バック", primary: true },
    { from: "turtle", to: "front-headlock", label: "首を取る", summary: "頭が下がったら前から束ねる。", relation: "コントロール" },
    { from: "turtle", to: "calf-slicer", label: "カーフスライサー", summary: "脚が絡んだ反応を圧迫技へ変える。", relation: "極め" },
    { from: "front-headlock", to: "guillotine", label: "ギロチン", summary: "首が深く入ったら前から絞める。", relation: "極め", primary: true },
    { from: "front-headlock", to: "darce", label: "ダース", summary: "脇下から腕を通して絞める。", relation: "極め" },
    { from: "front-headlock", to: "anaconda", label: "アナコンダ", summary: "首と腕をまとめてロールする。", relation: "極め" },
    { from: "front-headlock", to: "back-control", label: "バックへ回る", summary: "相手が防御したら背中側を取る。", relation: "バック" },
    { from: "shrimp-escape", to: "half-guard", label: "ハーフへ戻す", summary: "膝を入れて片脚を絡める。", relation: "復帰", primary: true },
    { from: "shrimp-escape", to: "closed-guard", label: "クローズドへ戻す", summary: "両脚を戻して腰を閉じる。", relation: "復帰" },
    { from: "side-control-escape", to: "shrimp-escape", label: "エビで空間を作る", summary: "フレームから腰を逃がす。", relation: "脱出", primary: true },
    { from: "side-control-escape", to: "half-guard", label: "ハーフへ戻す", summary: "内側へ膝を差し込む。", relation: "復帰" },
    { from: "mount-escape", to: "bridge-roll", label: "ブリッジロール", summary: "ポストを消して斜めへ返す。", relation: "脱出", primary: true },
    { from: "mount-escape", to: "elbow-knee-escape", label: "肘膝で戻す", summary: "膝を内側へ入れてハーフへ戻る。", relation: "脱出" },
    { from: "bridge-roll", to: "closed-guard", label: "上を取られてガードへ", summary: "返した後にトップ側のガード内になる。", relation: "出口", primary: true },
    { from: "elbow-knee-escape", to: "half-guard", label: "ハーフへ", summary: "片脚を絡めてパスを止める。", relation: "復帰", primary: true },
    { from: "back-escape", to: "half-guard", label: "ハーフへ落とす", summary: "肩を床につけて脚を絡める。", relation: "復帰", primary: true },
    { from: "back-escape", to: "turtle", label: "タートルへ", summary: "首を守りながら四つん這いへ戻る。", relation: "復帰" },
    { from: "turtle-recovery", to: "standing", label: "立ちへ戻る", summary: "相手のグリップを切って立ち上がる。", relation: "復帰", primary: true },
    { from: "turtle-recovery", to: "single-leg", label: "片脚を拾う", summary: "相手の前足を取って攻めに変える。", relation: "カウンター" },
    { from: "turtle-recovery", to: "open-guard", label: "ガードへ戻る", summary: "内側スペースを作り脚を戻す。", relation: "復帰" },
    { from: "straight-ankle-lock", to: "fifty-fifty", label: "50/50を確認する", summary: "足関節の攻防を続ける。", relation: "継続" },
    { from: "toe-hold", to: "fifty-fifty", label: "50/50へ戻る", summary: "相手の反撃も含めて脚の絡みを確認する。", relation: "継続" },
    { from: "heel-hook", to: "fifty-fifty", label: "脚の絡みに戻る", summary: "ルールと安全を確認しながら位置へ戻る。", relation: "継続" },
  ],
  drawings: {
    standing: {
      className: "drawing-standing",
      viewBox: "0 0 900 680",
      markup: `
        <path d="M92 470 C198 378 260 424 342 316 C442 184 552 246 640 142 C708 62 792 88 850 44" />
        <path d="M180 520 C272 454 346 460 448 388 C546 318 624 302 760 292" />
        <circle cx="342" cy="316" r="16" />
        <circle cx="640" cy="142" r="11" />
        <circle cx="760" cy="292" r="12" />
      `,
    },
    guard: {
      className: "drawing-guard",
      viewBox: "0 0 900 680",
      markup: `
        <path d="M130 426 C220 266 358 242 454 348 C552 456 686 430 790 256" />
        <path d="M156 258 C260 430 386 456 504 336 C610 230 712 276 806 416" />
        <circle cx="454" cy="348" r="24" />
        <circle cx="252" cy="350" r="12" />
        <circle cx="694" cy="354" r="12" />
      `,
    },
    pass: {
      className: "drawing-pass",
      viewBox: "0 0 900 680",
      markup: `
        <path d="M118 514 H326 C432 514 466 446 466 356 V148 H766" />
        <path d="M248 430 H596 C710 430 760 374 798 310" />
        <path d="M700 106 L766 148 L700 190" />
        <rect x="424" y="314" width="84" height="84" rx="14" />
        <circle cx="326" cy="514" r="12" />
      `,
    },
    control: {
      className: "drawing-control",
      viewBox: "0 0 900 680",
      markup: `
        <rect x="180" y="160" width="220" height="134" rx="20" />
        <rect x="500" y="250" width="220" height="134" rx="20" />
        <path d="M400 228 C488 220 516 252 564 318" />
        <path d="M270 294 C312 416 430 488 592 520" />
        <circle cx="592" cy="520" r="16" />
      `,
    },
    submission: {
      className: "drawing-submission",
      viewBox: "0 0 900 680",
      markup: `
        <path d="M176 364 C214 180 406 126 548 236 C678 338 618 534 450 526 C314 520 274 384 368 310 C452 244 566 306 546 406" />
        <path d="M546 406 L604 348 L624 430" />
        <circle cx="368" cy="310" r="13" />
        <circle cx="546" cy="406" r="13" />
      `,
    },
    escape: {
      className: "drawing-escape",
      viewBox: "0 0 900 680",
      markup: `
        <path d="M144 508 C250 508 276 414 348 380 C436 338 508 402 590 342 C666 286 692 184 814 158" />
        <path d="M252 238 C356 206 432 252 474 326" />
        <path d="M744 112 L814 158 L744 210" />
        <circle cx="348" cy="380" r="14" />
        <circle cx="590" cy="342" r="14" />
      `,
    },
    flow: {
      className: "drawing-flow",
      viewBox: "0 0 900 680",
      markup: `
        <path d="M98 430 C220 300 360 394 462 250 C548 130 702 172 820 86" />
        <path d="M462 250 C502 390 626 442 778 396" />
        <circle cx="462" cy="250" r="16" />
        <circle cx="778" cy="396" r="12" />
      `,
    },
  },
};
